import Navbar from "@/comps/Navbar";
import DashboardNavbar from "@/comps/dashboard/DashboardNavbar/DashboardNavbar";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="flex min-h-screen flex-col">
      <Navbar />
      <div className="flex">
        <aside className="w-[15%] h-screen bg-white shadow-2xl">
          <DashboardNavbar />
        </aside>
        <main className="w-[calc(100%-15%)]">{children}</main>
      </div>
    </div>
  );
}
