import Navbar from "@/comps/Navbar"
import DashboardNavbar from "@/comps/dashboard/DashboardNavbar/DashboardNavbar"
import "@/styles/global.css"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div className="flex min-h-screen flex-col">
    <Navbar />
    <aside>
      <DashboardNavbar />
    </aside>
    <div>
      {children}
    </div>
  </div>
  )
}
