import { DashboardSideNav } from "@cs/components/sidenav"
import { siteConfig } from "@cs/config/site"
import { Icons } from "@cs/components/icons"
import { TopNav } from "@cs/components/topnav"

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
}

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div className="flex min-h-screen flex-col">
      <div>
        <aside className="fixed inset-0 h-screen w-[80px] bg-cstetiary-900 transition-all md:w-[280px]">
          <div className="h-full px-2 py-6">
            <Icons.logo className="hidden h-[42px] md:block" />
            <Icons.mlogo className="h-[42px] md:hidden" />
            <hr className="my-4" />
            <DashboardSideNav items={siteConfig.dashSideNav} />
          </div>
        </aside>
        <main className="ml-[80px] transition-all md:ml-[280px]">
          <header className="sticky inset-0 ">
            <TopNav />
          </header>
          {children}
        </main>
      </div>
    </div>
  )
}
