import Navbar from "@/component/navbar/Navbar";
import DashboardNavbar from "@/component/dashboard/DashboardNavbar/DashboardNavbar";
import DashboardSidePannel from "@/component/dashboard/DashboardSidePannel";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="flex min-h-screen flex-col">
      <header className="sticky inset-0 ">
        <Navbar />
      </header>
      <div>
        <aside className="w-[250px] h-screen fixed inset-0 bg-white shadow-2xl">
          <DashboardSidePannel/>
        </aside>
        <main className="ml-[250px]">{children}</main>
      </div>
    </div>
  );
}
