// import "@/styles/global.css"
import "@/styles/global.css"
import { Inter as FontSans } from "next/font/google"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const fontSans = FontSans({
  variable: '--font-sans',
  subsets: ['latin']
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${fontSans.variable}`}>{children}</body>
    </html>
  )
}
